### ISSUE TITLE
支持一下，希望能够支持2020.1版本

### ISSUE THREAD

**Issue by zxhbloomer** [Link-Kou/intellij-mybaitslog#1]
非常感谢您的付出。如果能够支持2020.1版本，那就太好了。
如果提的issue格式不合理，请见谅。

**Comment by Link-Kou** [comment]
升级版本很快呢！我现在还再用2019.3.4版本。我怕很多插件来不及更新。就没有升级。有bug截图。稍迟一两个星期我会升级到2020.1版本。

**Comment by lvtanxi** [comment]
打不出sql来2020.1

**Comment by zxhbloomer** [comment]
好的，好东西就是要支持

**Comment by Link-Kou** [comment]
我测试一下，支持IDEA2020版本的。至于日志为什么不打印排查一下日志，插件基于日志来打印sql的。还有我特地重新使用2020SDK进行了重新的编译。
![image](https://user-images.githubusercontent.com/22113151/79629939-f20d2980-817f-11ea-8d53-5145df87e548.png)

**Comment by lvtanxi** [comment]
@Link-Kou 
![image](https://user-images.githubusercontent.com/16009130/79677413-96947780-8223-11ea-9956-2aae5e48467f.png)
2020.1控制台有sql，但mybatis log的确是没有sql。配置肯定是正确了的(之前mybatis log plugin)是可以打印的。请指教

**Comment by Link-Kou** [comment]
@lvtanxi  方便给我一下你的项目吗？ 我在我本机调试一下。

**Comment by lvtanxi** [comment]
[tyu.zip](https://github.com/Link-Kou/intellij-mybaitslog/files/4498466/tyu.zip)
这是我项目的简化版本，也是有问题的。sql在web的resources下面

**Comment by lvtanxi** [comment]
@Link-Kou

**Comment by Link-Kou** [comment]
@lvtanxi  收到

**Comment by Link-Kou** [comment]
@lvtanxi  

 [plugin.intellij.assistant.mybaitslog-2020.1-1.0.1.jar](https://raw.githubusercontent.com/Link-Kou/intellij-mybaitslog/master/plugin/plugin.intellij.assistant.mybaitslog-2020.1-1.0.1.jar)

试一下！我测试完成了。

**Comment by AprilViolet** [comment]
@Link-Kou 作者下载地址挂了QAQ
![image](https://user-images.githubusercontent.com/40155496/79690739-92517400-828e-11ea-958d-15de7468169e.png)

**Comment by Link-Kou** [comment]
@AprilViolet  同学，记得出门在外要扶墙而行。

**Comment by AprilViolet** [comment]
@AprilViolet 我开了代理啊，不应该啊，访问不了

**Comment by lvtanxi** [comment]
@Link-Kou 始终是没有，比较尴尬

**Comment by AprilViolet** [comment]
@lvtanxi 你也进不去那个网站下载么？直接下载443的错误

**Comment by Link-Kou** [comment]
@lvtanxi  可以先卸载插件，在安装试试看！
然后我录制了一个gif,你按我的操作试试看行不行！我拿你的demo试的

![2020-04-20_09-14-27 (1)](https://user-images.githubusercontent.com/22113151/79705232-8a71ee00-82e7-11ea-8954-2bc85959d900.gif)

**Comment by Link-Kou** [comment]
@AprilViolet  下载不了！那就留个邮件给我。我发你邮件

**Comment by AprilViolet** [comment]
@Link-Kou 哈哈，麻烦了1300957894@qq.com，感谢

**Comment by lvtanxi** [comment]
@Link-Kou ok了
