### ISSUE TITLE
重复打印日志

### ISSUE THREAD

**Issue by ShibaInu64** [Link-Kou/intellij-mybaitslog#10]
同一条记录打印两次
控制台输出：
DEBUG 10-06 13:05:44,265 ==>  Preparing: select * from tbl_employee where id=?  (BaseJdbcLogger.java:137) 
DEBUG 10-06 13:05:44,298 ==> Parameters: 5(Integer)  (BaseJdbcLogger.java:137) 
DEBUG 10-06 13:05:44,371 <==      Total: 1  (BaseJdbcLogger.java:137) 

插件输出：
--  DEBUG 10-06 13:05:44,265 ==>  
select
    * 
from
    tbl_employee 
where
    id=5(
        Integer
    )    (
        BaseJdbcLogger.java:137
    )  
 --  DEBUG 10-06 13:05:44,265 ==>  
select
    * 
from
    tbl_employee 
where
    id=5(
        Integer
    )    (
        BaseJdbcLogger.java:137
    )

**Comment by Link-Kou** [comment]
打印是通过，控制台输出获取日志，进行解析的，看一下控制台是否输出两条
