### ISSUE TITLE
5.0.7.3无法输出对应的sql，启动报错， idea版本2023.1

### ISSUE THREAD

**Issue by KevinWangMZ** [Link-Kou/intellij-mybaitslog#101]
Start: MyBatis Log EasyPlus
==>  SQLStructureError: javassist.NotFoundException: org.apache.ibatis.plugin.InterceptorChain
==>  SQLStructureError: javassist.NotFoundException: org.apache.ibatis.scripting.defaults.RawSqlSource

**Comment by Link-Kou** [comment]
@KevinWangMZ 
你的Mybatis版本是什么？

**Comment by KevinWangMZ** [comment]
Mybatis-plus 版本3.4.1

**Comment by KevinWangMZ** [comment]
嗯 当前项目是有依赖的 我这边换个项目试试看

**Comment by Link-Kou** [comment]
@KevinWangMZ  下载最新的版本试试看

**Comment by 1Elona** [comment]
求问一下解决了吗，同样的情况自己新建的项目可以输出但是公司的项目不行
