### ISSUE TITLE
都是折叠的。怎么设置默认展开

### ISSUE THREAD

**Issue by hanmengsjz** [Link-Kou/intellij-mybaitslog#102]
![image](https://user-images.githubusercontent.com/50688498/233600669-814125fa-cf21-48fc-885d-52c7d05c46a4.png)

**Comment by Link-Kou** [comment]
@hanmengsjz 哈哈
最近会更新掉，支持折叠展开

**Comment by Link-Kou** [comment]
@hanmengsjz 已经优化
