### ISSUE TITLE
有简约版的吗每次都弹出这个mybatisLogEasyPlu有点膈应

### ISSUE THREAD

**Issue by wosshitianming** [Link-Kou/intellij-mybaitslog#103]
不是说不支持作者哈,我用这玩意已经三四年了。还是2.0的版本好用，但是4.0的也不错，就是有个MyBatis Log EasyPlus的又换回2.0的去了，希望作者能把这个去掉吧，我觉得去掉会好看点，希望作者采纳，感谢
 ============================================================================ 

    MyBatis Log EasyPlus

    A mybatis javaagent framework :)

    https://github.com/Link-Kou/intellij-mybaitslog

  ============================================================================

**Comment by Link-Kou** [comment]
@wosshitianming  可以。没有问题。后续版本里加开关支持关闭
先忍一段时间先，我目前在解决加强兼容性和处理错误情况

**Comment by Link-Kou** [comment]
@wosshitianming 已经优化
