### ISSUE TITLE
5.0.7.5使用mybatis-plus LambdaQueryWrapper 或 QueryWrapper 时，between  date and date 解析有问题

### ISSUE THREAD

**Issue by Marswxq** [Link-Kou/intellij-mybaitslog#104]
5.0.7.5使用mybatis-plus LambdaQueryWrapper 或 QueryWrapper 时，between  date and date 解析有问题 ， 只能解析出来 BETWEEN '2023-04-01 00:00:00' ，AND 内容会有丢失

**Comment by Link-Kou** [comment]
@Marswxq 跟mybatis-plus兼容性问题后续会逐步加强测试覆盖，感谢反馈。

**Comment by Marswxq** [comment]
你好，我发现用mybatis写between and 解析也很会丢掉and 部分

**Comment by Link-Kou** [comment]
@Marswxq  经过测试mybatis输出between and 没有出现异常，你能发我一下xml里你是怎么书写的吗？

**Comment by Marswxq** [comment]
> 过测试mybatis输出between and 没有出现异常，你能发我一下xml里你是怎么书写的吗？
mapper关键内容如下：
FROM tableA C,
     tableB S
WHERE S.TIME BETWEEN #{lastTime} AND #{thisTime}

ps: 有没有可能是因为dao extends BaseMapper 导致的

**Comment by Link-Kou** [comment]
@Marswxq 收到，我最近会构建好测试用例，多多测试。

**Comment by Marswxq** [comment]
感谢作者

**Comment by Link-Kou** [comment]
@Marswxq 下载新版本。问题已经解决
