### ISSUE TITLE
Setting 关闭之后蒙层没有关闭，全局都是灰的

### ISSUE THREAD

**Issue by FormatToday** [Link-Kou/intellij-mybaitslog#105]
插件版本：5.0.7.5
idea 版本：IntelliJ IDEA 2023.1 (Ultimate Edition)

Filter Setting 打开之后其他地方不是会有蒙层变暗嘛，关闭 setting 界面之后蒙层没有关闭，全局都是灰的，需要重启idea才可解决

正常的样子：
![image](https://user-images.githubusercontent.com/20515769/234514182-8b1e86ff-07e1-4746-9b63-4b216aee1bb6.png)

现在蒙层未关闭的样子：
![image](https://user-images.githubusercontent.com/20515769/234513927-8f60e712-298c-4236-86ec-ba9f9729c7ca.png)

**Comment by Link-Kou** [comment]
@FormatToday 各位问题有点奇怪，我也是2023的没有碰到。感谢反馈，我测试一下。

**Comment by FormatToday** [comment]
经测试，是和Material Theme UI 、Atom Material File Icons这两个插件有关，估计只是和第一个有关，第二个不一定。
已提PR #106
