### ISSUE TITLE
条件查询OR丢失

### ISSUE THREAD

**Issue by git1071440198** [Link-Kou/intellij-mybaitslog#107]
mybaitslog 版本：5.0.7.6
 项目mybatis版本：<mybatis.version>3.3.1</mybatis.version>
mybatis.xml条件查询中含OR会丢失, 
 示例：正确SQL： select * from where 1=1 and (id =1 or id =2 )  mybaitslog回显的错误SQL: select * from where 1=1 and (id =1 )  

![image](https://user-images.githubusercontent.com/45163023/236406641-1147b101-63e1-4c84-a79a-4f25349a5097.png)

**Comment by Link-Kou** [comment]
@git1071440198 方便的话复制一下XML给我

**Comment by Link-Kou** [comment]
@git1071440198  下载最新版本，已经修复了此问题
