### ISSUE TITLE
查询语句有多个条件, 生成的sql只有一个

### ISSUE THREAD

**Issue by smous** [Link-Kou/intellij-mybaitslog#108]
插件版本: 5.0.7.6

sql日志:
Creating a new SqlSession
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@23322c12] was not registered for synchronization because synchronization is not active
JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@3fccdff3] will not be managed by Spring
==>  Preparing: SELECT id,require_id,require_no FROM table_require WHERE ((create_date >= ? AND create_date <= ?))
==> Parameters: 2023-03-01 00:00:00.0(Timestamp), 2023-05-01 00:00:00.0(Timestamp)

生成的sql: 
- -->  com.test.mapper.TableRequireMapper.selectList
    >  SELECT id,require_id,require_no FROM table_require WHERE ((create_date >= '2023-03-01 00:00:00'))

**Comment by smous** [comment]
sql日志:
JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@19ceac2a] will not be managed by Spring
==>  Preparing: SELECT id,require_id,require_no FROM table_require WHERE ((create_date >= ? AND create_date <= ?) OR (update_date >= ? AND update_date <= ?))
==> Parameters: 2023-03-01 00:00:00.0(Timestamp), 2023-05-01 00:00:00.0(Timestamp), 2023-03-01 00:00:00.0(Timestamp), 2023-05-01 00:00:00.0(Timestamp)


生成的sql: 
- -->  com.test.mapper.TableRequireMapper.selectList
    >  SELECT id,require_id,require_no FROM table_require WHERE ((create_date >= '2023-03-01 00:00:00'))

**Comment by Link-Kou** [comment]
@smous 方便的话发我一下XML

**Comment by smous** [comment]
> @smous 方便的话发我一下XML

这个是使用mybatis plus,   LambdaQueryWrapper 生成的sql

**Comment by Link-Kou** [comment]
@smous  请下载最新版本，问题已经修复

**Comment by smous** [comment]
> @smous 请下载最新版本，问题已经修复

@Link-Kou 感谢大佬!
