### ISSUE TITLE
启动网关服务等没有用到mybatis的服务就一直刷报错信息

### ISSUE THREAD

**Issue by aprilz-code** [Link-Kou/intellij-mybaitslog#109]
![image](https://github.com/Link-Kou/intellij-mybaitslog/assets/33222816/7392f706-74d0-44eb-8e73-0e6054ce6d42)

**Comment by aprilz-code** [comment]
想知道有排除一些服务的功能么

**Comment by Link-Kou** [comment]
![image](https://github.com/Link-Kou/intellij-mybaitslog/assets/22113151/3e761669-382c-43f7-9425-9bb0bda8dc20)
