### ISSUE TITLE
我想尝试sql注入，结果插件却不打印日志

### ISSUE THREAD

**Issue by hetintin** [Link-Kou/intellij-mybaitslog#110]
这是控制台输出的内容

SQLStructure: {"id":"com.checkuser","originalSql":"select\n\t\t*\n\t\tfrom sys_acc WHERE aid=#{aId}","completeSql":"select * from sys_acc WHERE app_id='cs' or '1=1'","parameter":"[{\"aId\":\"'cs' or '1=1'\"}]","total":0}

**Comment by Link-Kou** [comment]
@hetintin 麻烦提供一下XML

**Comment by Link-Kou** [comment]
@hetintin   你在试试最新版本

**Comment by Link-Kou** [comment]
@hetintin  我发布了新版本，在试一下
