### ISSUE TITLE
[BUG] ConcurrentModificationException

### ISSUE THREAD

**Issue by 4379711** [Link-Kou/intellij-mybaitslog#113]
> 插件版本: 5.0.7.7
> jdk: 1.8
## 问题复现:
1. 启动一个springboot应用(安装好插件并保证能正常打印sql),此时**不要发起请求**
2. **并发**请求任意能打印sql的接口,一般**并发量大于5**即可100%复现
3. 出现`java.util.ConcurrentModificationException`

## 问题定位
> 我没仔细读你的代码,**猜测**是`DynamicSqlSourceMonitor `中对`InterceptorChain.pluginAll`做操作时出现的线程安全问题
![image](https://github.com/Link-Kou/intellij-mybaitslog/assets/33949826/a7638db1-d8a9-4109-a7a8-50165416aeaf)

## 暂时性解决方案
1. 不使用插件(**不推荐**)
2. 每次服务启动后,先单独请求一个接口,把该加载的内容加载完后,再并发请求(**推荐**)
3. 作者修改插件(**强烈推荐**)

**Comment by Link-Kou** [comment]
@4379711 收到。

**Comment by Link-Kou** [comment]
@4379711 问题已经修复了
