### ISSUE TITLE
升级到5.0.8，不打印SQL

### ISSUE THREAD

**Issue by LZQSimonLee** [Link-Kou/intellij-mybaitslog#114]

**Comment by LZQSimonLee** [comment]
> @LZQSimonLee 看看设置情况。我测试是好的 ![image](https://user-images.githubusercontent.com/22113151/240458024-7aa3ec50-1fa3-4ca3-a586-19f811d58553.png)
> 
> ![image](https://user-images.githubusercontent.com/22113151/240457868-805cb1c2-82f1-4801-bdc0-7e9b6af0b782.png)

![image](https://github.com/Link-Kou/intellij-mybaitslog/assets/15881206/83a5f7b3-ee3a-4926-822c-f4cbae7a1b6a)

**Comment by Link-Kou** [comment]
@LZQSimonLee  关闭掉 RMIServer 输出。 然后关注一下 Exclude里是否有勾选你的执行器

**Comment by LZQSimonLee** [comment]
> @LZQSimonLee 关闭掉 RMIServer 输出。 然后关注一下 Exclude里是否有勾选你的执行器

可以了，谢谢

**Comment by LZQSimonLee** [comment]
![image](https://github.com/Link-Kou/intellij-mybaitslog/assets/15881206/f7525057-a944-484c-b329-0e5866294d54)
@Link-Kou 一直在打印这些，是啥

**Comment by Link-Kou** [comment]
@LZQSimonLee 你运行的服务中没有Mybatis。你可以关闭【运行提示】
