### ISSUE TITLE
启动项目总是会生成这个文件请问是为什么啊？

### ISSUE THREAD

**Issue by JC201806** [Link-Kou/intellij-mybaitslog#115]
<img width="1217" alt="image" src="https://github.com/Link-Kou/intellij-mybaitslog/assets/49872032/f9c21e73-d054-4af6-9fbb-a9343b4a06a6">

**Comment by Link-Kou** [comment]
版本是多少，不是最新版本升级一下。

**Comment by JC201806** [comment]
5.0.8
就是升级了最新版本才出现这个问题，之前的版本没有出现过这个文件夹


该邮件从移动设备发送


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Link-Kou/intellij-mybaitslog"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月26日(星期五) 下午2:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Link-Kou/intellij-mybaitslog] 启动项目总是会生成这个文件请问是为什么啊？ (Issue #115)





 
版本是多少，不是最新版本升级一下。

**Comment by Link-Kou** [comment]
确实是BUG我修复一下

**Comment by Link-Kou** [comment]
@JC201806 请在试一下新版本，我修复bug发布了

**Comment by lhd-1727865856** [comment]
新版本是多少
<img width="355" alt="image" src="https://github.com/Link-Kou/intellij-mybaitslog/assets/55698739/671ab680-2bcb-4d58-bf9d-0733dc5b9a9a">
这个版本还是会多出来这个文件
