### ISSUE TITLE
SQL不在Mybatis-Log弹出框中展示

### ISSUE THREAD

**Issue by lhd-1727865856** [Link-Kou/intellij-mybaitslog#117]
<img width="1568" alt="image" src="https://github.com/Link-Kou/intellij-mybaitslog/assets/55698739/8dc9d631-3f4a-411f-ad62-e7d714e1ae0c">
之前的版本有选中日志右键格式化SQL的功能,新版本没有那个按钮了。并且在MyBatis-Log的框里面也没有格式化之后的SQL
只有在<SQLStructure>这里有个SQL不太方便,是我哪里配置有问题吗？

**Idea Version: 2023.1.2**
**Plugin Version: 5.0.8.1**

**Comment by lhd-1727865856** [comment]
Version 5.0.8.1

**Comment by Link-Kou** [comment]
@lhd-1727865856 看看配置

![image](https://github.com/Link-Kou/intellij-mybaitslog/assets/22113151/7aa3ec50-1fa3-4ca3-a586-19f811d58553)

![image](https://github.com/Link-Kou/intellij-mybaitslog/assets/22113151/805cb1c2-82f1-4801-bdc0-7e9b6af0b782)

**Comment by lhd-1727865856** [comment]
@Link-Kou 是这个配置的问题。感谢！
