### ISSUE TITLE
IDEA最新版不支持，SQL没打印

### ISSUE THREAD

**Issue by HoRea98** [Link-Kou/intellij-mybaitslog#118]
![image](https://github.com/Link-Kou/intellij-mybaitslog/assets/66680816/be3d4559-66a3-4fb1-b245-fa4187ef6364)
![image](https://github.com/Link-Kou/intellij-mybaitslog/assets/66680816/dce57c25-4dd0-467e-ba9f-d581e1e031a4)
![image](https://github.com/Link-Kou/intellij-mybaitslog/assets/66680816/3a2d9df3-0113-48e3-8ecd-5e913a8bc54c)

**Comment by Link-Kou** [comment]
不要勾选RMIServer，去掉勾选即可。

**Comment by HoRea98** [comment]
您好，收到，稍后查看会尽快给您回复！

**Comment by HoRea98** [comment]
不勾选好像也不行

**Comment by HoRea98** [comment]
是不是不兼容最新版的，我降了IDEA的版本就能用，1.0的版本最新版也能兼容

**Comment by Link-Kou** [comment]
@HoRea98 收到，我再试试
