### ISSUE TITLE
启动以后无法捕获SQL，且启动一直输出这个

### ISSUE THREAD

**Issue by HappyDragon1994** [Link-Kou/intellij-mybaitslog#119]
![image](https://github.com/Link-Kou/intellij-mybaitslog/assets/60464328/f1cbce23-3677-4442-baa9-7378b3c74efe)

**Comment by HappyDragon1994** [comment]
idea版本为2020.3.4

**Comment by Link-Kou** [comment]
这个错误说明没有找到 mybatis 的依赖才会导致的。你看看是否依赖了mybatis
