### ISSUE TITLE
只有Preparing预编译的SQL，没有Parameters结果显示呀

### ISSUE THREAD

**Issue by qq34384878** [Link-Kou/intellij-mybaitslog#12]
![image](https://user-images.githubusercontent.com/18387058/97099547-1fa1d500-16c5-11eb-86b9-bb34ab7885f0.png)

**Comment by Link-Kou** [comment]
@qq34384878  输出的Parameters没有是由你执行的SQL本身就没有参数。还有就是Parameters结果不是由插件控制。
