### ISSUE TITLE
LocalDate类型，拼SQL错误

### ISSUE THREAD

**Issue by cheakin** [Link-Kou/intellij-mybaitslog#121]
当时间参数是LocalDate类型时,拼出来的SQL不对。

我的xml内容：
![image](https://github.com/Link-Kou/intellij-mybaitslog/assets/29295460/86a57552-4a3b-4302-8957-a4e1e5048346)
拼出来的SQL:
![image](https://github.com/Link-Kou/intellij-mybaitslog/assets/29295460/1254061d-a0ca-4256-a2ea-b39e4a545375)

时间少了引号，导致查出来的数据不对！

**Comment by Link-Kou** [comment]
@cheakin 收到，我调试一下

**Comment by Link-Kou** [comment]
@cheakin  我看了一下，时间是否加引号，取决你自己是否在XML中写。
输出时间不加引号是对的。
