### ISSUE TITLE
最新版本idea无法打印SQL

### ISSUE THREAD

**Issue by Oislop** [Link-Kou/intellij-mybaitslog#122]
Build #IU-231.9161.38, built on June 20, 2023 该版本无法打印SQL
已经禁用插件、重启idea。
只有重启日志输出
![image](https://github.com/Link-Kou/intellij-mybaitslog/assets/42344129/1ee2996d-527d-49ea-b4cc-7abe70c4788a)

**Comment by Link-Kou** [comment]
![image](https://github.com/Link-Kou/intellij-mybaitslog/assets/22113151/248ee13e-271e-499d-8507-ef38a202e75d)
关闭了就可以

**Comment by Oislop** [comment]
关闭了，也无法输出噢
![image](https://github.com/Link-Kou/intellij-mybaitslog/assets/42344129/4983e3a6-ef00-4152-8096-8570d89da930)

**Comment by Link-Kou** [comment]
奇怪？
你看看运行有没有报什么错误，

**Comment by Oislop** [comment]
> 

运行后无任何报错信息，也无任何日志输出噢~

**Comment by Oislop** [comment]
> > 
> 
> 运行后无任何报错信息，也无任何日志输出噢~

这个有弄个wx群交流嘛
