### ISSUE TITLE
解析出现 Illegal group reference

### ISSUE THREAD

**Issue by huanghunqingjiao** [Link-Kou/intellij-mybaitslog#127]
当保存字符串`[httpServerRequest[ org.springframework.security.web.header.HeaderWriterFilter$HeaderWriterRequest@67b80766]]`时，idea控制台出现`java.lang.IllegalArgumentException: Illegal group reference`异常
异常栈如下
![image](https://github.com/Link-Kou/intellij-mybaitslog/assets/35722374/a58bd03c-c8e9-4314-a86b-eccaebd68c44)
相关复现Demo代码：https://github.com/huanghunqingjiao/MyBatisLogEasyPlusBugDemo.git

**Comment by Link-Kou** [comment]
@huanghunqingjiao  问题收到。近期会更新

**Comment by Link-Kou** [comment]
@huanghunqingjiao  问题已经定位修复，待下个版本发布
