### ISSUE TITLE
string类型如果是[{"111":"222"}]的格式，会影响属性的判断，输出出现异常

### ISSUE THREAD

**Issue by ehehe066** [Link-Kou/intellij-mybaitslog#15]
这是数据格式
![1](https://user-images.githubusercontent.com/30278102/99762613-e62d7f80-2b33-11eb-8477-6dd1962ed627.png)

这是输出结果
![2](https://user-images.githubusercontent.com/30278102/99762632-ea599d00-2b33-11eb-84a5-b18c44e60c38.png)

开发者是否可以更新下匹配的规则，万分感谢

**Comment by Link-Kou** [comment]
@ehehe066 请问你的插件版本是多少? 我在最新的版本中解决了这个问题，如果升级到最新版本后依旧就有这个问题。请在留言给我，我在看一下

**Comment by Link-Kou** [comment]
@ehehe066  目前对JSON文本等一些需要有转义相关的文字不会转义。因为输出的时候都是String。我到时候升级一下，支持转义

**Comment by ehehe066** [comment]
> @ehehe066 请问你的插件版本是多少? 我在最新的版本中解决了这个问题，如果升级到最新版本后依旧就有这个问题。请在留言给我，我在看一下

您好，我这里用的版本是是最新的版本
![3](https://user-images.githubusercontent.com/30278102/99765884-f72dbf00-2b3a-11eb-8200-cac2d0f0bc3f.png)

**Comment by Link-Kou** [comment]
@ehehe066  请将日志文本复制给我一下。我测试一下

**Comment by ehehe066** [comment]
Console端口输出文本

13:17:00.087 [schedule-pool-8] DEBUG n.p.s.i.r.C.updateByPrimaryKeySelective - [debug,159] - ==>  Preparing: update "COLLABORATIVE_MANAGEMENT" SET "TASK_ID" = ?, "ISSUE_DATE" = ?, "ISSUE_PERSON" = ?, "ISSUE_PERSON_ID" = ?, "TYPE" = ?, "TASK_NAME" = ?, "COMPLETION_PERIOD" = ?, "COLLABORATIVE_RULE" = ?, "SYS_USER" = ?, "COLLABORATIVE_OBJECT" = ?, "EXECUTION_RULE" = ?, "EXECUTION_CONTENT" = ?, "TRIGGER_RULE" = ?, "LINKED_DATA_SOURCES" = ?, "PERIODICITY" = ?, "EXECUTIVE_UNIT" = ?, "MISSION_REQUIREMENT" = ?, "RELATED_ATTACHMENT" = ?, "TASK_STATUS" = ?, "SITE_SELECTION" = ?, "DIVISION" = ?, "EXECUTION_STATUS" = ? where "ID" = ? 
13:17:00.088 [schedule-pool-8] DEBUG n.p.s.i.r.C.updateByPrimaryKeySelective - [debug,159] - ==> Parameters: (String), 2020-11-07 00:00:00.0(Timestamp), 3(String), 74(Integer), 30(Integer), ddaaaaaaaaaaaaaaaaaaaaaaaa(String), 2020-11-04 00:00:00.0(Timestamp), 10(Integer), 2696(Integer), 刘明(String), 20(Integer), [{"feedback":"0","nowTask":"0","time":"2020-11-02 00:11:01","status":"10"},{"feedback":"0","nowTask":"0","time":"2020-12-09 00:12:03","status":"0"},{"feedback":"0","nowTask":"0","time":"2020-12-22 00:12:03","status":"0"},{"feedback":"0","nowTask":"0","time":"2020-12-06 00:12:03","status":"0"}](String), 10(Integer), ddd(String), (String), (String), 1616(String), (String), 10(Integer), (String), (String), (String), 1(Integer)

mybatis log端输出文本

update
    "COLLABORATIVE_MANAGEMENT" 
SET
    "TASK_ID" = (String),
    "ISSUE_DATE" = '2020-11-07 00:00:00.0',
    "ISSUE_PERSON" = '3',
    "ISSUE_PERSON_ID" = 74,
    "TYPE" = 30,
    "TASK_NAME" = 'ddaaaaaaaaaaaaaaaaaaaaaaaa',
    "COMPLETION_PERIOD" = '2020-11-04 00:00:00.0',
    "COLLABORATIVE_RULE" = 10,
    "SYS_USER" = 2696,
    "COLLABORATIVE_OBJECT" = '刘明',
    "EXECUTION_RULE" = 20,
    "EXECUTION_CONTENT" = [{"feedback":"0", "TRIGGER_RULE" = "nowTask":"0", "LINKED_DATA_SOURCES" = "time":"2020-11-02 00:11:01", "PERIODICITY" = "status":"10"}, "EXECUTIVE_UNIT" = {"feedback":"0", "MISSION_REQUIREMENT" = "nowTask":"0", "RELATED_ATTACHMENT" = "time":"2020-12-09 00:12:03", "TASK_STATUS" = "status":"0"}, "SITE_SELECTION" = {"feedback":"0", "DIVISION" = "nowTask":"0", "EXECUTION_STATUS" = "time":"2020-12-22 00:12:03" where "ID" = "status":"0"}

**Comment by Link-Kou** [comment]
@ehehe066  问题解决了，你下载最新的1.0.7版本，在测试一下。

**Comment by ehehe066** [comment]
十分感谢开发者，问题已经解决了
