### ISSUE TITLE
希望增加 格式化与不格式化的按钮功能

### ISSUE THREAD

**Issue by l7810** [Link-Kou/intellij-mybaitslog#16]
1.0.7版本中，安装在idea 2020.2.3中，启用插件，就开启了格式化SQL的功能。希望 用户可以通过某个按钮，直接格式化或则不可视化显示。

很多情况下，当发现有异常时，再启用格式化是个很好的客户体验。

![image](https://user-images.githubusercontent.com/12392453/100416087-92cdab00-30b8-11eb-8bfb-e709d6ee7ccb.png)

**Comment by Link-Kou** [comment]
@l7810  调研一下你的需求
1、你希望是针对特定sql格式化，而其他sql不需要格式化？
2、通过按钮来进行格式化开启，你希望之前已经输出的sql是否进行格式化？
3、发生异常在格式化，其实日志都无法输出出来。我想知道你的异常场景是？

**Comment by l7810** [comment]
1、不是！ 针对整个控制台的，很多时候，不是每条SQL都需要进行格式化的。正常换行就行了。当调试功能时，可能会对特定的几条数据进行调试时，则需要格式化，这个动作，一般都是开发人员操作。所以，建议增加一个可自由控制 是否格式化的按钮即可。

2、以前的格式化可以不用理会。之前是什么样就是什么样，保持不变即可。

3、发生异常的SQL，都没有进入插件这边，所以没用使用场景。

**Comment by Link-Kou** [comment]
@l7810 好的，收到

**Comment by Link-Kou** [comment]
@l7810  添加了需求的功能。
