### ISSUE TITLE
对mysql中的like语句无法正常替换值啊

### ISSUE THREAD

**Issue by suucx** [Link-Kou/intellij-mybaitslog#20]
AND `name` LIKE CONCAT(%s,'%') ) 只要包含这种语句就不行

**Comment by Link-Kou** [comment]
@suucx  辛苦一下，截图一下给我

**Comment by suucx** [comment]
> @suucx辛苦 一下，截图一下给我
![image](https://user-images.githubusercontent.com/61496579/102440427-2c0a3480-405b-11eb-9365-f0b305ada464.png)
如果sql中有这种like语句模糊查询就会导致sql参数全部无法填充,具体表现形式就是这样。

**Comment by Link-Kou** [comment]
@suucx  把日志输出结果也贴一下

**Comment by suucx** [comment]
> @suucx 把日志输出结果也贴一下

![image](https://user-images.githubusercontent.com/61496579/102443488-d4bb9280-4061-11eb-8f4d-284a43195544.png)

**Comment by Link-Kou** [comment]
@suucx 已经解决，发布了。下载安装最新版本
