### ISSUE TITLE
安装后在插件中心不显示

### ISSUE THREAD

**Issue by fangweilong** [Link-Kou/intellij-mybaitslog#4]
你好 提一个不算是bug的小问题
我下载jar包以后离线安装 虽然是安装成功了 但是在插件中心是看不到这个插件的 通过在控制台右键可以查看到 不知道是idea问题还是插件问题
idea版本：2020.1

**Comment by Link-Kou** [comment]
我没有明白你的意思
我可以理解为，你需要的是下图的内容吗？

![image](https://user-images.githubusercontent.com/22113151/83609004-39287000-a5b0-11ea-8dd6-b1283a01197b.png)

**Comment by fangweilong** [comment]
图裂了 
![image](https://user-images.githubusercontent.com/20884749/83622514-ae04a580-a5c2-11ea-9ddb-11b46c33376a.png)
就是第一次安装在plgins中找不到这个插件，但是功能是正常用

**Comment by Link-Kou** [comment]
@fangweilong  看你发的图，工具是存在的。 
你所描述的  第一次安装 在插件中心无法显示的问题。可以用无敌大法处理。重启IDEA。好用而且实用
