### ISSUE TITLE
你好，请问支持2020.2版本吗

### ISSUE THREAD

**Issue by oday-xiexin** [Link-Kou/intellij-mybaitslog#6]
你好，请问支持2020.2版本吗

**Comment by oday-xiexin** [comment]
我现在是2020.1版本可以用，怕升级到2020.2该插件不能用了，这个插件很好用，不兼容就不升级了

**Comment by Link-Kou** [comment]
@oday-xiexin 稍微等等。要在试用版本上测试。SDK我也没有下载过来--！，SDK下载太慢了，心都是累的。
我这段时间也准备升级。我也是在等周边的插件支持2020.2 。每一次升级都是一场插件兼容大考验。
我现在用的2020.1，到现在还有一些插件没有及时升级过来。到今天为止都不能用
