### ISSUE TITLE
sql语句里面的正则出现的问号会影响参数的正常替换。

### ISSUE THREAD

**Issue by baymaxxjf** [Link-Kou/intellij-mybaitslog#62]
sql语句里面的正则出现的问号会影响参数的正常替换。

**Comment by Link-Kou** [comment]
截图给我一下。 原sql给我一下。谢谢了

**Comment by baymaxxjf** [comment]
插件控制台显示的sql
select
&nbsp; &nbsp; &nbsp; &nbsp; "trade_way" :: jsonb -&gt; 0 -&gt;&gt;0 AS tradeWay,
&nbsp; &nbsp; &nbsp; &nbsp; COALESCE( sum(substring("trade_way"::jsonb -&gt; 0 -&gt;&gt; 1,
&nbsp; &nbsp; &nbsp; &nbsp; '(-%s([0-9]*)(.[0-9]+)%s)')::NUMERIC ),
&nbsp; &nbsp; &nbsp; &nbsp; 0) as amount&nbsp;
&nbsp; &nbsp; from
&nbsp; &nbsp; &nbsp; &nbsp; "hisMatch_2021" as t1&nbsp;
&nbsp; &nbsp; left join
&nbsp; &nbsp; &nbsp; &nbsp; "his_2021" as t2&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; on t1.his_id = t2.id&nbsp;
&nbsp; &nbsp; WHERE
&nbsp; &nbsp; &nbsp; &nbsp; t1.is_invalid = 0&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; and "trade_way" :: jsonb -&gt; 0 -&gt;&gt;0 is not null&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; and his_id in (
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; %s , %s , %s , %s , %s , %s , %s , %s , %s , %s , %s , %s , %s , %s , %s , %s , %s , %s , %s , %s , %s , %s , %s , %s , %s&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; )&nbsp;
&nbsp; &nbsp; group by
&nbsp; &nbsp; &nbsp; &nbsp; tradeWay

原sql:
select
"trade_way" :: jsonb -&gt; 0 -&gt;&gt;0 AS tradeWay,
COALESCE( sum(substring("trade_way"::jsonb -&gt; 0 -&gt;&gt; 1,'(-?([0-9]*)(.[0-9]+)?)')::NUMERIC ),0) as amount
from
"${hisMatchTableName}" as t1
left join
"${hisTableName}" as t2
on t1.his_id = t2.id
<where&gt;
    cast(matching_result -&gt; 0 -&gt;&gt; 'recordId' as INTEGER) = #{recordId}
    and "trade_way" :: jsonb -&gt; 0 -&gt;&gt;0 is not null
    and t1.is_invalid = 0
</where&gt;
group by
tradeWay


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Link-Kou/intellij-mybaitslog"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月25日(星期一) 中午12:02
收件人:&nbsp;"Link-Kou/intellij-mybaitslog"<intellij-mybaitslog@noreply.github.com&gt;;
抄送:&nbsp;"JX"<1340324168@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Link-Kou/intellij-mybaitslog] sql语句里面的正则出现的问号会影响参数的正常替换。 (#62)





 
截图给我一下。 原sql给我一下。谢谢了

**Comment by Link-Kou** [comment]
@baymaxxjf  建议用代码块 包裹一下 。特殊字符串被格式化了。不好处理

**Comment by baymaxxjf** [comment]
这里处理？
<sql id="common_sql0"&gt;
    COALESCE( sum(substring("trade_way"::jsonb -&gt; 0 -&gt;&gt; 1,'(-?([0-9]*)(.[0-9]+)?)')::NUMERIC ),0) as amount
</sql&gt;
好像不行。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Link-Kou/intellij-mybaitslog"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月25日(星期一) 中午12:18
收件人:&nbsp;"Link-Kou/intellij-mybaitslog"<intellij-mybaitslog@noreply.github.com&gt;;
抄送:&nbsp;"JX"<1340324168@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Link-Kou/intellij-mybaitslog] sql语句里面的正则出现的问号会影响参数的正常替换。 (#62)





 
@baymaxxjf  建议用代码块 包裹一下 。特殊字符串被格式化了。不好处理

**Comment by baymaxxjf** [comment]
> @baymaxxjf 建议用代码块 包裹一下 。特殊字符串被格式化了。不好处理
``` sql
      select
            "trade_way" :: jsonb -> 0 ->>0 AS tradeWay,
            COALESCE( sum(substring("trade_way"::jsonb -> 0 ->> 1,
            '(-%s([0-9]*)(.[0-9]+)%s)')::NUMERIC ),
            0) as amount 
        from
            "hisMatch_2020" as t1 
        left join
            "his_2020" as t2 
                on t1.his_id = t2.id 
        WHERE
            cast(matching_result -> 0 ->> 'recordId' as INTEGER) = %s 
            and "trade_way" :: jsonb -> 0 ->>0 is not null 
            and t1.is_invalid = 0 
        group by
            tradeWay 
```
原sql:
``` sql
select
    "trade_way" :: jsonb -> 0 ->>0 AS tradeWay,
    COALESCE( sum(substring("trade_way"::jsonb -> 0 ->> 1,'(-?([0-9]*)(.[0-9]+)?)')::NUMERIC ),0) as amount
    from
    "${hisMatchTableName}" as t1
    left join
    "${hisTableName}" as t2
    on t1.his_id = t2.id
    <where>
        cast(matching_result -> 0 ->> 'recordId' as INTEGER) = #{recordId}
        and "trade_way" :: jsonb -> 0 ->>0 is not null
        and t1.is_invalid = 0
    </where>
    group by
    tradeWay
```

**Comment by Link-Kou** [comment]
@baymaxxjf  已经修复此问题，当是由于mysql函数很多，目前就支持了substring，其他函数如果还有问题。欢迎随时Issues
