### ISSUE TITLE
2.0 安装错误

### ISSUE THREAD

**Issue by smalljop** [Link-Kou/intellij-mybaitslog#63]
Plugin 'MybatisLog' (version '2.0.0') is not compatible with the current version of the IDE, because it requires build 230 or newer but the current build is IU-203.7148.57

IntelliJ IDEA 2020.3.2 (Ultimate Edition)
Build #IU-203.7148.57, built on January 26, 2021
Subscription is active until December 15, 2021.
For non-commercial open source development only.
Runtime version: 11.0.9.1+11-b1145.77 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: debugger.watches.in.variables=false, compiler.automake.allow.when.app.running=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: Key Promoter X, com.jetbrains.CyanTheme, com.jetbrains.grayTheme, com.samdark.intellij-visual-studio-code-dark-plus, commit-template-idea-plugin, de.netnexus.camelcaseplugin, net.vektah.codeglance, mobi.hsz.idea.gitignore, name.kropp.intellij.makefile, String Manipulation, com.alibaba.p3c.smartfox, org.intellij.gitee, MavenRunHelper, com.alibabacloud.intellij.toolkit-intellij, org.jetbrains.kotlin, com.codota.csp.intellij, com.viartemev.requestmapper, zielu.gittoolbox, JRebelPlugin, jr-mp-ide-idea, cn.wuzhizhan.plugin.mybatis, com.sjhy.plugin.easycode, cn.yiiguxing.plugin.translate, com.baomidou.plugin.idea.mybatisx, com.github.mustfun.plugin.mybatis, com.biyusheng.plugins, com.linkkou.plugin.intellij.assistant.mybaitslog

**Comment by Link-Kou** [comment]
我升级到IDEA 2020.3这个版本了。这个版本是使用Java11环境的。如果没有java11,就无法运行
建议：clone源代码按照本机idea环境，重新构建一下就可以。
