### ISSUE TITLE
2020.3.2无法安装

### ISSUE THREAD

**Issue by scemsjyd** [Link-Kou/intellij-mybaitslog#65]

**Comment by Link-Kou** [comment]
@scemsjyd  截图给我看一下。

**Comment by AmazingDM** [comment]
![image](https://user-images.githubusercontent.com/10679055/107107970-83fd3480-686f-11eb-98cd-78fcf4de2075.png)

**Comment by AmazingDM** [comment]
![image](https://user-images.githubusercontent.com/10679055/107107977-911a2380-686f-11eb-9c52-1e07ac6f0cab.png)

**Comment by vual** [comment]
是一样的问题，3.2安装提示版本不对，提示需要idea230版本以上。

**Comment by Link-Kou** [comment]
因为我升级到最新的

![image](https://user-images.githubusercontent.com/22113151/107174596-9610db80-6a05-11eb-82f8-4444e14618b0.png)

这个版本采用是java11的。我之前的老版本我没有装。编译我也采用了java11。无法向后兼容插件了。

解决这个问题就是采用 2020.3.2 以下的版本编译以下，即可

**Comment by chengmengwang** [comment]
![image](https://user-images.githubusercontent.com/44402117/107516626-a4b6e880-6be7-11eb-9df9-91233a28ae9d.png)
![image](https://user-images.githubusercontent.com/44402117/107516666-b4cec800-6be7-11eb-8730-73e826f87a98.png)
您好，我的版本应该和您是一样的，我还是无法安装，我使用IDEA2019.3.5版本将源码重新编译并打成jar之后还是无法安装

**Comment by Link-Kou** [comment]
我重新编译了，再次安装2.0.1版本。
