### ISSUE TITLE
Specified localPath '/Applications/IntelliJ IDEA.app' doesn't exist or is not a directory

### ISSUE THREAD

**Issue by 8debug** [Link-Kou/intellij-mybaitslog#66]
在构建中遇到的问题

![image](https://user-images.githubusercontent.com/3394927/108297394-243f4b80-71d6-11eb-9ce9-a17fa96eaf0b.png)

**Comment by Link-Kou** [comment]
@8debug  这样子的，我的是mac系统，换到win系统需要将 localpath 改为IDea安装目录就可
