### ISSUE TITLE
sql语句输出时候希望保留参数原有格式

### ISSUE THREAD

**Issue by LambdaV5** [Link-Kou/intellij-mybaitslog#76]
sql语句参数前面如果有空格，这个插件会自动去除空格、导致实际执行的sql和打印出来的sql有出入。
比如真实查询语句为select module_id from ss_role_module where role_id = ' 1aebb396-2aa1-4136-9f3a-45681a978081'
输出后为select module_id from ss_role_module where role_id = '1aebb396-2aa1-4136-9f3a-45681a978081'；这样会掩盖错误，望支持修复

**Comment by Link-Kou** [comment]
@LambdaV5 收到
