### ISSUE TITLE
打印的日志没有序号和文件信息显示

### ISSUE THREAD

**Issue by hagyao520** [Link-Kou/intellij-mybaitslog#77]
效果：
![image](https://user-images.githubusercontent.com/24785603/145926814-3cf732f5-2ab2-4404-9334-2a1d8ded5005.png)
目前：
![image](https://user-images.githubusercontent.com/24785603/145926717-e7511ede-125a-49dd-912c-f9e9c0f06435.png)

**Comment by hagyao520** [comment]
@Link-Kou

**Comment by Link-Kou** [comment]
@hagyao520  收到

**Comment by Link-Kou** [comment]
@hagyao520  
看一下 日志配置方式。我这里测试好的

**Comment by hagyao520** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    
    <property name="log.path" value="logs" />
    
	
    
	<property name="log.pattern" value="%d{HH:mm:ss.SSS} [%thread] %-5level %logger{20} - [%method,%line] - %msg%n" />

	
	<appender name="console" class="ch.qos.logback.core.ConsoleAppender">
		<encoder>
			<pattern>${log.pattern}</pattern>
		</encoder>
	</appender>
	
	
	<appender name="file_info" class="ch.qos.logback.core.rolling.RollingFileAppender">
	    <file>${log.path}/sys-info.log</file>
        
		<rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            
			<fileNamePattern>${log.path}/sys-info.%d{yyyy-MM-dd}.log</fileNamePattern>
			
			<maxHistory>60</maxHistory>
		</rollingPolicy>
		<encoder>
			<pattern>${log.pattern}</pattern>
		</encoder>
		<filter class="ch.qos.logback.classic.filter.LevelFilter">
            
            <level>error</level>
            
            <onMatch>ACCEPT</onMatch>
            
            <onMismatch>DENY</onMismatch>
        </filter>
	</appender>
	
	<appender name="file_error" class="ch.qos.logback.core.rolling.RollingFileAppender">
	    <file>${log.path}/sys-error.log</file>
        
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            
            <fileNamePattern>${log.path}/sys-error.%d{yyyy-MM-dd}.log</fileNamePattern>
			
			<maxHistory>60</maxHistory>
        </rollingPolicy>
        <encoder>
            <pattern>${log.pattern}</pattern>
        </encoder>
        <filter class="ch.qos.logback.classic.filter.LevelFilter">
            
            <level>ERROR</level>
			
            <onMatch>ACCEPT</onMatch>
			
            <onMismatch>DENY</onMismatch>
        </filter>
    </appender>
	
	
    <appender name="sys-user" class="ch.qos.logback.core.rolling.RollingFileAppender">
		<file>${log.path}/sys-user.log</file>
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            
            <fileNamePattern>${log.path}/sys-user.%d{yyyy-MM-dd}.log</fileNamePattern>
            
            <maxHistory>60</maxHistory>
        </rollingPolicy>
        <encoder>
            <pattern>${log.pattern}</pattern>
        </encoder>
    </appender>
	
	
	<logger name="com.aidex" level="error" />
	
	<logger name="org.springframework" level="error" />

	<root level="error">
		<appender-ref ref="console" />
	</root>
	
	
    <root level="error">
        <appender-ref ref="file_info" />
        <appender-ref ref="file_error" />
    </root>
	
	
    <logger name="sys-user" level="error">
        <appender-ref ref="sys-user"/>
    </logger>
</configuration>

**Comment by hagyao520** [comment]
这个是我的配置，你那边是怎么配置的 @Link-Kou

**Comment by Link-Kou** [comment]
@hagyao520 直接输出com下面的。 

```xml

<!-- 控制台输出 -->
<appender name="console" class="com">
	<encoder>
		<pattern>${log.pattern}</pattern>
	</encoder>
</appender>

```
