### ISSUE TITLE
这个和在线插件仓库的Mybatis Log plugin是一个吗？看着好像。

### ISSUE THREAD

**Issue by Lc-1995** [Link-Kou/intellij-mybaitslog#78]
这个和在线插件仓库的Mybatis Log plugin是一个吗？看着好像。

**Comment by oday-xiexin** [comment]
一个收费一个免费

**Comment by Lc-1995** [comment]
> 一个收费一个免费

这个我知道🤣，就是除了这个，功能上有区别吗。

**Comment by oday-xiexin** [comment]
> > 一个收费一个免费
> 
> 这个我知道🤣，就是除了这个，功能上有区别吗。

这个插件就是输出日志 基础功能好用就行。花边功能没有

**Comment by Lc-1995** [comment]
> > > 一个收费一个免费
> > 
> > 
> > 这个我知道🤣，就是除了这个，功能上有区别吗。
> 
> 这个插件就是输出日志 基础功能好用就行。花边功能没有

好哒，感谢大佬分享。😃
