### ISSUE TITLE
希望能新增total显示，就是最终执行sql的记录数，目前的话在flter setting不知道怎么设置，应该是没有这种功能。filter settings多加一个Total:

### ISSUE THREAD

**Issue by jarpp** [Link-Kou/intellij-mybaitslog#79]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Link-Kou** [comment]
没有看明白意思

**Comment by Link-Kou** [comment]
V3.0.1解决此问题
