### ISSUE TITLE
不能自动打印sql了

### ISSUE THREAD

**Issue by gzvincen** [Link-Kou/intellij-mybaitslog#8]
项目刚启动后，还可以根据日志自动打印sql。清屏后，就没有办法自动打印sql了。不知道啥原因

IntelliJ IDEA 2020.2 (Ultimate Edition)
Build #IU-202.6397.94, built on July 27, 2020
Licensed to vincen eason
Subscription is active until September 3, 2020
For educational use only.
Runtime version: 11.0.7+10-b944.20 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Non-Bundled Plugins: com.alayouni.ansiHighlight, Lombook Plugin, String Manipulation, VisualVMLauncher, com.bruce.intellijpluin.stackoverflow, com.ccnode.codegenerator.mybatis.generator, com.github.setial, com.intellij.plugins.thrift, jclasslib, com.alibaba.p3c.smartfox, com.linkkou.plugin.intellij.assistant.mybaitslog, com.tang, de.netnexus.camelcaseplugin, MavenRunHelper, com.bruce.intellijplugin.generatesetter, com.zhaow.restful.toolkit, cn.wuzhizhan.plugin.mybatis, cn.yiiguxing.plugin.translate, izhangzhihao.rainbow.brackets

**Comment by Link-Kou** [comment]
@gzvincen   我会测试。

**Comment by oday-xiexin** [comment]
> @gzvincen 我会测试。

这个问题 大佬你定位到问题并fix了吗

**Comment by Link-Kou** [comment]
@oday-xiexin 你也有这个问题? 

我测试的结果，暂时没有发现情况。
截图错误消息。我会跟好的判断。

**Comment by oday-xiexin** [comment]
> @oday-xiexin 你也有这个问题?
> 
> 我测试的结果，暂时没有发现情况。
> 截图错误消息。我会跟好的判断。

我试下，我刚升到最新版本
