### ISSUE TITLE
批量插入，sql只显示第一个内容。

### ISSUE THREAD

**Issue by 1415749952** [Link-Kou/intellij-mybaitslog#80]
==>  Preparing: INSERT INTO DAILY_OUT ( ID, BATCH_CODE, START_TIME, END_TIME, FACORY_CODE, FACORY_NAME, PROD_LINE_CODE, PROD_LINE_NAME, PRODUCT_MODEL, STIR_OUTPUT_QUANTITY, PRE_HE_OUTPUT_QUANTITY, OCV1_OUTPUT_QUANTITY, CREATED_TIME, DEL_FLAG ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )
==> Parameters: 24ce80b1-be00-419e-b678-14c65fe78c02(String), 78f9122b-73a1-431a-930c-85214cdec7cb(String), 2022-02-09 00:00:00.0(Timestamp), 2022-02-10 00:00:00.0(Timestamp), 4010(String), 8J(String), 81(String), 81产线(String), LF230(String), 0(String), 2725(String), 3616(String), 2022-03-03 20:44:03.6(Timestamp), 0(String)
==> Parameters: 49d92de9-1f0d-4f90-b2a0-f5ab5ca5f129(String), 78f9122b-73a1-431a-930c-85214cdec7cb(String), 2022-02-09 00:00:00.0(Timestamp), 2022-02-10 00:00:00.0(Timestamp), 4010(String), 8J(String), 82(String), 82产线(String), LF230(String), 0(String), 0(String), 4414(String), 2022-03-03 20:44:03.773(Timestamp), 0(String)
==> Parameters: 23c955af-8aac-4402-83fb-335f4c86f077(String), 78f9122b-73a1-431a-930c-85214cdec7cb(String), 2022-02-09 00:00:00.0(Timestamp), 2022-02-10 00:00:00.0(Timestamp), 4010(String), 8J(String), 83(String), 83产线(String), LF280K(String), 0(String), 5449(String), 5392(String), 2022-03-03 20:44:03.953(Timestamp), 0(String)
==> Parameters: 7f37bb4f-a5dc-4674-a857-7df9fdec4bf3(String), 78f9122b-73a1-431a-930c-85214cdec7cb(String), 2022-02-09 00:00:00.0(Timestamp), 2022-02-10 00:00:00.0(Timestamp), 4010(String), 8J(String), 84(String), 84产线(String), LF280K(String), 0(String), 5002(String), 3776(String), 2022-03-03 20:44:04.132(Timestamp), 0(String)
==> Parameters: 491cbc2f-ae9a-4ac2-be88-a04bf1073071(String), 3ceecf48-ff3e-41ec-9b27-065de66d6670(String), 2022-02-10 00:00:00.0(Timestamp), 2022-02-11 00:00:00.0(Timestamp), 4010(String), 8J(String), 81(String), 81产线(String), LF230(String), 0(String), 3044(String), 3408(String), 2022-03-03 20:44:04.304(Timestamp), 0(String)
==> Parameters: 80b2d0f4-8810-4c85-a560-26a62beb8cbc(String), 3ceecf48-ff3e-41ec-9b27-065de66d6670(String), 2022-02-10 00:00:00.0(Timestamp), 2022-02-11 00:00:00.0(Timestamp), 4010(String), 8J(String), 82(String), 82产线(String), LF230(String), 0(String), 548(String), 480(String), 2022-03-03 20:44:04.476(Timestamp), 0(String)
==> Parameters: e9171382-6a78-48fd-8f0f-5b63d0abbf0c(String), 3ceecf48-ff3e-41ec-9b27-065de66d6670(String), 2022-02-10 00:00:00.0(Timestamp), 2022-02-11 00:00:00.0(Timestamp), 4010(String), 8J(String), 83(String), 83产线(String), LF280K(String), 0(String), 6717(String), 4928(String), 2022-03-03 20:44:04.708(Timestamp), 0(String)
==> Parameters: 52bc4b6c-cc06-481b-99d3-53cda7f003df(String), 3ceecf48-ff3e-41ec-9b27-065de66d6670(String), 2022-02-10 00:00:00.0(Timestamp), 2022-02-11 00:00:00.0(Timestamp), 4010(String), 8J(String), 84(String), 84产线(String), LF280K(String), 0(String), 4605(String), 2816(String), 2022-03-03 20:44:04.895(Timestamp), 0(String)
==> Parameters: 9d3dd40c-7e3b-49ad-94b0-2ef34d45bc60(String), 7d32db7a-763b-408e-91a6-3af8e7f0190d(String), 2022-02-09 00:00:00.0(Timestamp), 2022-02-10 00:00:00.0(Timestamp), 4090(String), 9J(String), 92(String), 92产线(String), C40(String), 0(String), 0(String), 10347(String), 2022-03-03 20:44:05.085(Timestamp), 0(String)
==> Parameters: 264bb4e8-ae9e-414a-9ede-edfc6e64cc36(String), 7d32db7a-763b-408e-91a6-3af8e7f0190d(String), 2022-02-09 00:00:00.0(Timestamp), 2022-02-10 00:00:00.0(Timestamp), 4090(String), 9J(String), 91(String), 91产线(String), C32(String), 0(String), 0(String), 10347(String), 2022-03-03 20:44:05.265(Timestamp), 0(String)
==>  Preparing: INSERT INTO DAILY_OUT ( ID, BATCH_CODE, START_TIME, END_TIME, FACORY_CODE, FACORY_NAME, PROD_LINE_CODE, PROD_LINE_NAME, PRODUCT_MODEL, STIR_OUTPUT_QUANTITY, PRE_HE_OUTPUT_QUANTITY, OCV1_OUTPUT_QUANTITY, CREATED_TIME, DEL_FLAG ) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )
==> Parameters: 2abc679e-dfb1-4144-a975-98e0327cec19(String), c5ed419d-b0e6-4f8d-90d6-0b6bc3237d09(String), 2022-02-10 00:00:00.0(Timestamp), 2022-02-11 00:00:00.0(Timestamp), 4090(String), 9J(String), 92(String), 92产线(String), C40(String), 0(String), 0(String), 510(String), 2022-03-03 20:44:05.433(Timestamp), 0(String)
==> Parameters: a972a390-2863-4ec3-a711-f06cb860dedd(String), c5ed419d-b0e6-4f8d-90d6-0b6bc3237d09(String), 2022-02-10 00:00:00.0(Timestamp), 2022-02-11 00:00:00.0(Timestamp), 4090(String), 9J(String), 91(String), 91产线(String), C32(String), 0(String), 0(String), 510(String), 2022-03-03 20:44:05.61(Timestamp), 0(String)
打印的SQL为
 --  ==>  
INSERT 
INTO
    DAILY_OUT
    ( ID, BATCH_CODE, START_TIME, END_TIME, FACORY_CODE, FACORY_NAME, PROD_LINE_CODE, PROD_LINE_NAME, PRODUCT_MODEL, STIR_OUTPUT_QUANTITY, PRE_HE_OUTPUT_QUANTITY, OCV1_OUTPUT_QUANTITY, CREATED_TIME, DEL_FLAG ) 
VALUES
    ( '24ce80b1-be00-419e-b678-14c65fe78c02', '78f9122b-73a1-431a-930c-85214cdec7cb', '2022-02-09 00:00:00.0', '2022-02-10 00:00:00.0', '4010', '8J', '81', '81产线', 'LF230', '0', '2725', '3616', '2022-03-03 20:44:03.6', '0' ) 
 --  ==>  
INSERT 
INTO
    DAILY_OUT
    ( ID, BATCH_CODE, START_TIME, END_TIME, FACORY_CODE, FACORY_NAME, PROD_LINE_CODE, PROD_LINE_NAME, PRODUCT_MODEL, STIR_OUTPUT_QUANTITY, PRE_HE_OUTPUT_QUANTITY, OCV1_OUTPUT_QUANTITY, CREATED_TIME, DEL_FLAG ) 
VALUES
    ( '2abc679e-dfb1-4144-a975-98e0327cec19', 'c5ed419d-b0e6-4f8d-90d6-0b6bc3237d09', '2022-02-10 00:00:00.0', '2022-02-11 00:00:00.0', '4090', '9J', '92', '92产线', 'C40', '0', '0', '510', '2022-03-03 20:44:05.433', '0' )

**Comment by Link-Kou** [comment]
@1415749952  这个确实是有问题的。待修复
