### ISSUE TITLE
3.0 是不是需要代码侵入才能生效？

### ISSUE THREAD

**Issue by aimilin6688** [Link-Kou/intellij-mybaitslog#82]
3.0版本 控制台日志 右键没有 mybatis-log 选项，是不是需要代码中配置并拦截才能生效？

**Comment by Link-Kou** [comment]
是的，因为老的版本无法解决一些极端的sql写法sql解析问题

<dependency>
    <groupId>com.github.link-kou</groupId>
    <artifactId>mybatis-plugin</artifactId>
    <version>1.0.0</version>
</dependency>

**Comment by Link-Kou** [comment]
新版本采用了代码侵入性，就目前而是最有效的解决sql格式化输出的问题，同时也解决生产环境也需要的格式化输出sql 的问题

至于非侵入式的我也在办法。因为mybatis日志输入的 ？号，实际上很多的sql写法也有，格式化容易出现问题

**Comment by duanluan** [comment]
> 新版本采用了代码侵入性，就目前而是最有效的解决 sql 格式化输出的问题，同时也解决生产环境也需要的格式化输出 sql 的问题
> 
> 至于非侵入式的我也在办法。因为 mybatis 日志输入的 ？号，实际上很多的 sql 写法也有，格式化容易出现问题

我有个 Spring MVC + MyBatis + JSP + Oracle 的老项目，之前用 V2.0.6 会出现 SQL 结尾出现多余的“>”，然后 Integer 参数出现多余的“Integer>”等。

然后我换成 V3.0.0 了，这样配置的，但是数据库报错了就。
```html
<bean id="logInterceptor" class="com.linkkou.mybatis.log.LogInterceptor"/>

<bean id="sqlSessionFactory" class="org.mybatis.spring.SqlSessionFactoryBean">
  <!-- …… -->
  <property name="plugins" ref="logInterceptor"/>
<bean>
```

**Comment by Link-Kou** [comment]
@duanluan  Spring MVC 要等一下。我现在优先支持boot。SpringMVC还需要在测试一下支持上是有问题

**Comment by Link-Kou** [comment]
@duanluan  我测试了一下，发现还是版本的问题，


mybatis-spring至少要以下版本,并且mybatis5以上，我用的spring-webmvc是5.3.22，测试没有问题

```xml 
<dependency>
			<groupId>org.mybatis</groupId>
			<artifactId>mybatis-spring</artifactId>
			<version>2.0.7</version>
		</dependency>
```

**Comment by Link-Kou** [comment]
@duanluan 后面我会尝试支持低版本。大概率是可以支持的

**Comment by Link-Kou** [comment]
@duanluan  我测试一下 只要是mybatis3以上都支持的。你的项目能把敏感信息删除了，发我一份吗？我测试一下。
