### ISSUE TITLE
新版本只有底栏显示输出日志区域，右键菜单没有相关功能了

### ISSUE THREAD

**Issue by Leonsama** [Link-Kou/intellij-mybaitslog#83]
![QQ截图20220825145326](https://user-images.githubusercontent.com/36270646/186595820-be69edf6-ce9e-4e9e-bbeb-9dd5e3a0e5a2.png)

**Comment by Link-Kou** [comment]
新版本采用了代码侵入性，就目前而是最有效的解决sql格式化输出的问题，同时也解决生产环境也需要的格式化输出sql 的问题
#82

**Comment by Link-Kou** [comment]
现在不需要右键菜单了。会自动会读取控制台的输出，如果体验不习惯。我想想后续在加上
