### ISSUE TITLE
与Jrebel and Xrebel插件一起使用时，启动项目会有报错

### ISSUE THREAD

**Issue by meiMingle** [Link-Kou/intellij-mybaitslog#87]
idea20233.1，jrebel and xrebel 20233.2.0，MyBatis Log EasyPlus 5.0.1

通过jrebel的run按钮启动项目时，出现报错
<details><pre>
C:\Users\Maria\.jdks\zulu8.68.0.21-ca-fx-jdk8.0.362-win_x64\bin\java.exe -javaagent:D:/dev_soft/ja-netfilter/ja-netfilter.jar -Drebel.base=C:\Users\Maria\.jrebel -Drebel.env.ide.plugin.version=2023.2.0 -Drebel.env.ide.version=2023.1 -Drebel.env.ide.product=IU -Drebel.env.ide=intellij -Drebel.notification.url=http://localhost:17434 -javaagent:C:\Users\Maria\AppData\Roaming\JetBrains\IntelliJIdea2023.1\plugins\jr-ide-idea\lib\xrebel\xrebel.jar -javaagent:C:\Users\Maria\AppData\Roaming\JetBrains\IntelliJIdea2023.1\plugins\MybatisLog\lib\mybatis-agent-1.0.19-all.jar -javaagent:C:\Users\Maria\AppData\Roaming\JetBrains\IntelliJIdea2023.1\plugins\MybatisLog\lib\mybatis-agent-1.0.19-all.jar -javaagent:D:\dev_soft\ideaIU-2023.1.win\lib\idea_rt.jar=52273:D:\dev_soft\ideaIU-2023.1.win\bin -Dfile.encoding=UTF-8 -classpath C:\Users\Maria\.jdks\zulu8.68.0.21-ca-fx-jdk8.0.362-win_x64\jre\lib\cat.jar;C:\Users\Maria\.jdks\zulu8.68.0.21-ca-fx-jdk8.0.362-win_x64\jre\lib\charsets.jar;C:\Users\Maria\.jdks\zulu8.68.0.21-ca-fx-jdk8.0.362-win_x64\jre\lib\ext\access-bridge-64.jar;C:\Users\Maria\.jdks\zulu8.68.0.21-ca-fx-jdk8.0.362-win_x64\jre\lib\ext\cldrdata.jar;C:\Users\Maria\.jdks\zulu8.68.0.21-ca-fx-jdk8.0.362-win_x64\jre\lib\ext\crs-agent.jar;C:\Users\Maria\.jdks\zulu8.68.0.21-ca-fx-jdk8.0.362-win_x64\jre\lib\ext\dnsns.jar;C:\Users\Maria\.jdks\zulu8.68.0.21-ca-fx-jdk8.0.362-win_x64\jre\lib\ext\jaccess.jar;C:\Users\Maria\.jdks\zulu8.68.0.21-ca-fx-jdk8.0.362-win_x64\jre\lib\ext\jfxrt.jar;C:\Users\Maria\.jdks\zulu8.68.0.21-ca-fx-jdk8.0.362-win_x64\jre\lib\ext\localedata.jar;C:\Users\Maria\.jdks\zulu8.68.0.21-ca-fx-jdk8.0.362-win_x64\jre\lib\ext\nashorn.jar;C:\Users\Maria\.jdks\zulu8.68.0.21-ca-fx-jdk8.0.362-win_x64\jre\lib\ext\sunec.jar;C:\Users\Maria\.jdks\zulu8.68.0.21-ca-fx-jdk8.0.362-win_x64\jre\lib\ext\sunjce_provider.jar;C:\Users\Maria\.jdks\zulu8.68.0.21-ca-fx-jdk8.0.362-win_x64\jre\lib\ext\sunmscapi.jar;C:\Users\Maria\.jdks\zulu8.68.0.21-ca-fx-jdk8.0.362-win_x64\jre\lib\ext\sunpkcs11.jar;C:\Users\Maria\.jdks\zulu8.68.0.21-ca-fx-jdk8.0.362-win_x64\jre\lib\ext\zipfs.jar;C:\Users\Maria\.jdks\zulu8.68.0.21-ca-fx-jdk8.0.362-win_x64\jre\lib\jce.jar;C:\Users\Maria\.jdks\zulu8.68.0.21-ca-fx-jdk8.0.362-win_x64\jre\lib\jfr.jar;C:\Users\Maria\.jdks\zulu8.68.0.21-ca-fx-jdk8.0.362-win_x64\jre\lib\jfxswt.jar;C:\Users\Maria\.jdks\zulu8.68.0.21-ca-fx-jdk8.0.362-win_x64\jre\lib\jsse.jar;C:\Users\Maria\.jdks\zulu8.68.0.21-ca-fx-jdk8.0.362-win_x64\jre\lib\management-agent.jar;C:\Users\Maria\.jdks\zulu8.68.0.21-ca-fx-jdk8.0.362-win_x64\jre\lib\resources.jar;C:\Users\Maria\.jdks\zulu8.68.0.21-ca-fx-jdk8.0.362-win_x64\jre\lib\rt.jar;D:\ideaProjects\mpdemo\target\classes;C:\Users\Maria\.m2\repository\org\springframework\boot\spring-boot-starter\1.5.4.RELEASE\spring-boot-starter-1.5.4.RELEASE.jar;C:\Users\Maria\.m2\repository\org\springframework\boot\spring-boot\1.5.4.RELEASE\spring-boot-1.5.4.RELEASE.jar;C:\Users\Maria\.m2\repository\org\springframework\boot\spring-boot-autoconfigure\1.5.4.RELEASE\spring-boot-autoconfigure-1.5.4.RELEASE.jar;C:\Users\Maria\.m2\repository\org\springframework\boot\spring-boot-starter-logging\1.5.4.RELEASE\spring-boot-starter-logging-1.5.4.RELEASE.jar;C:\Users\Maria\.m2\repository\ch\qos\logback\logback-classic\1.1.11\logback-classic-1.1.11.jar;C:\Users\Maria\.m2\repository\ch\qos\logback\logback-core\1.1.11\logback-core-1.1.11.jar;C:\Users\Maria\.m2\repository\org\slf4j\jcl-over-slf4j\1.7.25\jcl-over-slf4j-1.7.25.jar;C:\Users\Maria\.m2\repository\org\slf4j\jul-to-slf4j\1.7.25\jul-to-slf4j-1.7.25.jar;C:\Users\Maria\.m2\repository\org\slf4j\log4j-over-slf4j\1.7.25\log4j-over-slf4j-1.7.25.jar;C:\Users\Maria\.m2\repository\org\springframework\spring-core\4.3.9.RELEASE\spring-core-4.3.9.RELEASE.jar;C:\Users\Maria\.m2\repository\org\yaml\snakeyaml\1.17\snakeyaml-1.17.jar;C:\Users\Maria\.m2\repository\org\springframework\boot\spring-boot-starter-web\1.5.4.RELEASE\spring-boot-starter-web-1.5.4.RELEASE.jar;C:\Users\Maria\.m2\repository\org\springframework\boot\spring-boot-starter-tomcat\1.5.4.RELEASE\spring-boot-starter-tomcat-1.5.4.RELEASE.jar;C:\Users\Maria\.m2\repository\org\apache\tomcat\embed\tomcat-embed-core\8.5.15\tomcat-embed-core-8.5.15.jar;C:\Users\Maria\.m2\repository\org\apache\tomcat\embed\tomcat-embed-el\8.5.15\tomcat-embed-el-8.5.15.jar;C:\Users\Maria\.m2\repository\org\apache\tomcat\embed\tomcat-embed-websocket\8.5.15\tomcat-embed-websocket-8.5.15.jar;C:\Users\Maria\.m2\repository\org\hibernate\hibernate-validator\5.3.5.Final\hibernate-validator-5.3.5.Final.jar;C:\Users\Maria\.m2\repository\javax\validation\validation-api\1.1.0.Final\validation-api-1.1.0.Final.jar;C:\Users\Maria\.m2\repository\org\jboss\logging\jboss-logging\3.3.1.Final\jboss-logging-3.3.1.Final.jar;C:\Users\Maria\.m2\repository\com\fasterxml\classmate\1.3.3\classmate-1.3.3.jar;C:\Users\Maria\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.8.8\jackson-databind-2.8.8.jar;C:\Users\Maria\.m2\repository\com\fasterxml\jackson\core\jackson-annotations\2.8.0\jackson-annotations-2.8.0.jar;C:\Users\Maria\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.8.8\jackson-core-2.8.8.jar;C:\Users\Maria\.m2\repository\org\springframework\spring-web\4.3.9.RELEASE\spring-web-4.3.9.RELEASE.jar;C:\Users\Maria\.m2\repository\org\springframework\spring-aop\4.3.9.RELEASE\spring-aop-4.3.9.RELEASE.jar;C:\Users\Maria\.m2\repository\org\springframework\spring-beans\4.3.9.RELEASE\spring-beans-4.3.9.RELEASE.jar;C:\Users\Maria\.m2\repository\org\springframework\spring-webmvc\4.3.9.RELEASE\spring-webmvc-4.3.9.RELEASE.jar;C:\Users\Maria\.m2\repository\org\springframework\spring-expression\4.3.9.RELEASE\spring-expression-4.3.9.RELEASE.jar;C:\Users\Maria\.m2\repository\org\projectlombok\lombok\1.18.24\lombok-1.18.24.jar;C:\Users\Maria\.m2\repository\org\slf4j\slf4j-api\1.7.25\slf4j-api-1.7.25.jar;C:\Users\Maria\.m2\repository\org\springframework\spring-context\4.3.9.RELEASE\spring-context-4.3.9.RELEASE.jar;C:\Users\Maria\.m2\repository\org\springframework\spring-tx\4.3.9.RELEASE\spring-tx-4.3.9.RELEASE.jar;C:\Users\Maria\.m2\repository\com\baomidou\mybatis-plus-boot-starter\3.5.2\mybatis-plus-boot-starter-3.5.2.jar;C:\Users\Maria\.m2\repository\com\baomidou\mybatis-plus\3.5.2\mybatis-plus-3.5.2.jar;C:\Users\Maria\.m2\repository\com\baomidou\mybatis-plus-extension\3.5.2\mybatis-plus-extension-3.5.2.jar;C:\Users\Maria\.m2\repository\com\baomidou\mybatis-plus-core\3.5.2\mybatis-plus-core-3.5.2.jar;C:\Users\Maria\.m2\repository\com\baomidou\mybatis-plus-annotation\3.5.2\mybatis-plus-annotation-3.5.2.jar;C:\Users\Maria\.m2\repository\com\github\jsqlparser\jsqlparser\4.4\jsqlparser-4.4.jar;C:\Users\Maria\.m2\repository\org\mybatis\mybatis\3.5.10\mybatis-3.5.10.jar;C:\Users\Maria\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib-jdk8\1.6.21\kotlin-stdlib-jdk8-1.6.21.jar;C:\Users\Maria\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib\1.6.21\kotlin-stdlib-1.6.21.jar;C:\Users\Maria\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib-common\1.6.21\kotlin-stdlib-common-1.6.21.jar;C:\Users\Maria\.m2\repository\org\jetbrains\annotations\13.0\annotations-13.0.jar;C:\Users\Maria\.m2\repository\org\jetbrains\kotlin\kotlin-stdlib-jdk7\1.6.21\kotlin-stdlib-jdk7-1.6.21.jar;C:\Users\Maria\.m2\repository\org\springframework\boot\spring-boot-starter-jdbc\1.5.4.RELEASE\spring-boot-starter-jdbc-1.5.4.RELEASE.jar;C:\Users\Maria\.m2\repository\org\apache\tomcat\tomcat-jdbc\8.5.15\tomcat-jdbc-8.5.15.jar;C:\Users\Maria\.m2\repository\org\apache\tomcat\tomcat-juli\8.5.15\tomcat-juli-8.5.15.jar;C:\Users\Maria\.m2\repository\org\springframework\spring-jdbc\4.3.9.RELEASE\spring-jdbc-4.3.9.RELEASE.jar;C:\Users\Maria\.m2\repository\com\github\pagehelper\pagehelper-spring-boot-starter\1.4.6\pagehelper-spring-boot-starter-1.4.6.jar;C:\Users\Maria\.m2\repository\org\mybatis\spring\boot\mybatis-spring-boot-starter\2.2.2\mybatis-spring-boot-starter-2.2.2.jar;C:\Users\Maria\.m2\repository\org\mybatis\spring\boot\mybatis-spring-boot-autoconfigure\2.2.2\mybatis-spring-boot-autoconfigure-2.2.2.jar;C:\Users\Maria\.m2\repository\org\mybatis\mybatis-spring\2.0.7\mybatis-spring-2.0.7.jar;C:\Users\Maria\.m2\repository\com\github\pagehelper\pagehelper-spring-boot-autoconfigure\1.4.6\pagehelper-spring-boot-autoconfigure-1.4.6.jar;C:\Users\Maria\.m2\repository\com\github\pagehelper\pagehelper\5.3.2\pagehelper-5.3.2.jar;C:\Users\Maria\.m2\repository\org\mariadb\jdbc\mariadb-java-client\1.5.9\mariadb-java-client-1.5.9.jar;C:\Users\Maria\.m2\repository\com\google\zxing\core\3.5.0\core-3.5.0.jar com.example.mpdemo.MpdemoApplication

2023-04-05 23:47:57.137 XRebel: Starting logging to file: C:\Users\Maria\.xrebel\xrebel.log
2023-04-05 23:47:58.877 XRebel: 
2023-04-05 23:47:58.877 XRebel: ################################################################
2023-04-05 23:47:58.878 XRebel: 
2023-04-05 23:47:58.878 XRebel:  XRebel Agent 2021.3.1 (202303051600)
2023-04-05 23:47:58.878 XRebel:  (c) Copyright 2007-2021 Perforce Software, Inc.
2023-04-05 23:47:58.878 XRebel: 
2023-04-05 23:47:58.878 XRebel:  For questions and support, contact support@xrebel.com
2023-04-05 23:47:58.878 XRebel: 
2023-04-05 23:47:58.878 XRebel: ################################################################
2023-04-05 23:47:58.878 XRebel: 
MybatisPlugins
MybatisPlugins
javassist.CannotCompileException: by java.lang.ClassFormatError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: "org/apache/ibatis/plugin/InterceptorChain"
	at javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:271)
	at javassist.ClassPool.toClass(ClassPool.java:1240)
	at javassist.CtClass.toClass(CtClass.java:1392)
	at com.plugins.mybaitslog.monitor.DynamicSqlSourceMonitor.transform(DynamicSqlSourceMonitor.java:47)
	at com.plugins.mybaitslog.transformer.transform(transformer.java:36)
	at com.plugins.mybaitslog.preAgent.premain(preAgent.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.ClassFormatError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: "org/apache/ibatis/plugin/InterceptorChain"
	at javassist.util.proxy.DefineClassHelper$Java7.defineClass(DefineClassHelper.java:182)
	at javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:260)
	... 11 more
javassist.CannotCompileException: by java.lang.ClassFormatError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: "org/apache/ibatis/scripting/defaults/RawSqlSource"
	at javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:271)
	at javassist.ClassPool.toClass(ClassPool.java:1240)
	at javassist.CtClass.toClass(CtClass.java:1392)
	at com.plugins.mybaitslog.monitor.RawSqlSourceMonitor.transform(RawSqlSourceMonitor.java:45)
	at com.plugins.mybaitslog.transformer.transform(transformer.java:36)
	at com.plugins.mybaitslog.preAgent.premain(preAgent.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.ClassFormatError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: "org/apache/ibatis/scripting/defaults/RawSqlSource"
	at javassist.util.proxy.DefineClassHelper$Java7.defineClass(DefineClassHelper.java:182)
	at javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:260)
	... 11 more
</pre></details>

**Comment by Link-Kou** [comment]
@meiMingle 

java17 需要添加
```xml
--add-opens java.base/java.lang=ALL-UNNAMED
```
请手动添加一下：
![image](https://user-images.githubusercontent.com/22113151/230248140-12cf6eb6-72da-4fb8-939a-76911ced7366.png)


自动的，目前在优化中。预计本周就可以发布

**Comment by meiMingle** [comment]
@Link-Kou 然而加上这个参数之后彻底无法启动了。
![image](https://user-images.githubusercontent.com/39942874/230282441-0aa2b770-9c07-4b42-b962-c220f9aea0f2.png)

**Comment by Link-Kou** [comment]
@meiMingle  我已经下载了jrebel（2022.4.1 ）在测试中，最新版本的jrebel（2023.2.0）没有找到pojie的地方。我先测试jrebel（2022.4.1 ）

**Comment by meiMingle** [comment]
> @meiMingle 我已经下载了jrebel（2022.4.1 ）在测试中，最新版本的jrebel（2023.2.0）没有找到pojie的地方。我先测试jrebel（2022.4.1 ）

https://github.com/Nasller/LicenseServer

**Comment by Link-Kou** [comment]
@meiMingle  jrebel（2022.4.1 ） 测试没有问题。可以执行。
jrebel最新版本在MAC上pojie无效。你现在我最新发布的版本看看。是否可以执行。

先运行一边，然后勾选里面的boot执行器。考虑到现在的执行器实在是太多了。加入这个排除项能力
![image](https://user-images.githubusercontent.com/22113151/230299060-5108f06d-4594-4bcc-9417-9c5fa0c2aaaf.png)

**Comment by Link-Kou** [comment]
@meiMingle 问题我重现出来了。感谢你的反馈

**Comment by Link-Kou** [comment]
@meiMingle 你之前有引用5.0之前的JAR到你的项目中吗？

**Comment by meiMingle** [comment]
@Link-Kou 你指的是哪个jar呢？

**Comment by Link-Kou** [comment]
```xml
<dependency>
            <groupId>com.github.link-kou</groupId>
            <artifactId>mybatis-plugin</artifactId>
            <version>1.1.0</version>
        </dependency>
```

**Comment by meiMingle** [comment]
@Link-Kou 没有哇，从来没引用过这个

**Comment by Link-Kou** [comment]
@meiMingle 你现在升级到最新的版本了吗？ 5.0.3的版本

**Comment by meiMingle** [comment]
我试试哈

**Comment by Link-Kou** [comment]
@meiMingle 主要问题还有一个是就在非Debug模式下会报错，但是可是使用。我现在还在定位中

**Comment by meiMingle** [comment]
@Link-Kou 5.0.3 虽然启动不报错了，但是也抓不到sql了

**Comment by meiMingle** [comment]
发现一个问题，就是最开始的时候（idea20233.1，jrebel and xrebel 20233.2.0，MyBatis Log EasyPlus 5.0.1）

**Comment by meiMingle** [comment]
发现一个问题，就是最开始的时候（idea20233.1，jrebel and xrebel 20233.2.0，MyBatis Log EasyPlus 5.0.1）
通过jrebel的run按钮启动项目时，控制台打印的命令里mybatis-agent出现了两次。
![image](https://user-images.githubusercontent.com/39942874/230349496-175be1c7-7d87-4779-a0aa-102a5fa5a4b5.png)

**Comment by Link-Kou** [comment]
@meiMingle 我发现了，最新版本已经改进了，你下载5.0.4看看

**Comment by meiMingle** [comment]
@Link-Kou 5.0.4 你没发安装包包
![image](https://user-images.githubusercontent.com/39942874/230372414-b1addf02-2212-4a7e-a729-bdac9ae9ddc8.png)

**Comment by Link-Kou** [comment]
@meiMingle  我的问题，已经补充上去了

**Comment by meiMingle** [comment]
@Link-Kou 5.0.4和5.0.5 我都试了，还是不行。错误日志跟5.0.1一样

**Comment by Link-Kou** [comment]
@meiMingle 这让我感受到无穷的挫败感。
看看重新卸载插件、重新按照看看呢。

**Comment by meiMingle** [comment]
@Link-Kou 没事老铁，我周末debug试试能不能找出猫腻，搞不好时jrebel的问题

**Comment by meiMingle** [comment]
@Link-Kou 抱歉老铁，我试了好半天没跑起来这个代码。但是也许修改PerRun.java的55行能修复这个问题，你有空的话修改一下打个包我再试试。
```java

            String agentParameter = "-javaagent:" + agentCoreJarPath;
            if (!vmParametersList.hasParameter(agentParameter)) {
                vmParametersList.prepend(agentParameter);
            }
```

**Comment by Link-Kou** [comment]
@meiMingle 收到，我在debug试一下

**Comment by Link-Kou** [comment]
@meiMingle 
手动下载 5.0.7 。测试一下。

**Comment by Link-Kou** [comment]
@meiMingle 有时间，在现在最新版本的在测试一下。

**Comment by meiMingle** [comment]
@Link-Kou 5.0.7.1不好使，启动是没报错，但是也抓不到sql了，控制台命令里面没有mybatis-agent

**Comment by Link-Kou** [comment]
@meiMingle 
现在可以下载最新的5.0.7.2，我添加了错误提示输出，可以看看到底是哪里的问题
[MybatisLog-5.0.7.2.zip](https://github.com/Link-Kou/intellij-mybaitslog/files/11220766/MybatisLog-5.0.7.2.zip)

**Comment by meiMingle** [comment]
@Link-Kou 5.0.7.2一切正常
