### ISSUE TITLE
stackoverflow

### ISSUE THREAD

**Issue by tank520** [Link-Kou/intellij-mybaitslog#88]
使用mybatisplus getOne查询时 gson会出现stackoverflow异常

**Comment by Link-Kou** [comment]
@tank520 有截图或报错信息吗？ 用的版本几？

**Comment by tank520** [comment]
插件版本：5.0.1，没截图我现在还原到老版本了

**Comment by tank520** [comment]
感觉是把Wrapper给打出来了，导致stackoverflow

**Comment by Link-Kou** [comment]
@tank520   安装 5.0.3的版本。麻烦然后在试一下。

**Comment by Link-Kou** [comment]
@tank520  记得运行后。
开启一下拦截器。后续版本中会自动开启的
![image](https://user-images.githubusercontent.com/22113151/230340790-c5fe438f-d79b-49ea-b9b3-b2c696453197.png)

**Comment by tank520** [comment]
这个配置在哪？没找到

**Comment by Link-Kou** [comment]
@tank520 
![image](https://user-images.githubusercontent.com/22113151/230343479-01ef8cf8-93bd-4447-b6c2-e9c3a0200a51.png)

**Comment by tank520** [comment]
![image](https://user-images.githubusercontent.com/25721782/230359788-e0aaa78b-2c95-4be4-bcb7-58e4a65ca849.png)

**Comment by tank520** [comment]
![image](https://user-images.githubusercontent.com/25721782/230359864-72ff0f6a-fc4f-476a-90a4-7ba9ff9784e1.png)
还是报错

**Comment by Link-Kou** [comment]
1、你是使用了类似于Mybatis Plus的框架吗？
2、方便的SQL脱敏发我一下吗？
@tank520

**Comment by tank520** [comment]
1、是用的mybatis plus
2、调用com.baomidou.mybatisplus.extension.service.IService下的default T getOne(Wrapper<T> queryWrapper)就会报错

**Comment by storyxc** [comment]
+1，下午更新后也发现了这个问题，也是mybatis-plus，调用其他方法也能复现，我是使用了Mapper的selectCount出现的。

**Comment by Link-Kou** [comment]
@tank520 @storyxc 
稍等等我测试一下，大概率有什么地方和mybatis-plus不兼容

**Comment by Link-Kou** [comment]
我用5.0.4测试没有出现过错误。
你们调用getOne可以给个代码吗？我照着测试

**Comment by Link-Kou** [comment]
@tank520 @storyxc 
IDEA 插件商城还在审核中，可以先本机安装

**Comment by storyxc** [comment]
> 我用5.0.4测试没有出现过错误。 你们调用getOne可以给个代码吗？我照着测试

应该用Wrapper查询就会出现问题 比如
```java
Integer count = testMapper.selectCount(
                Wrappers.<Test>lambdaQuery()
                        .eq(Test::getId, 1)
        );
```
