### ISSUE TITLE
字符类型的没加上引号

### ISSUE THREAD

**Issue by oday-xiexin** [Link-Kou/intellij-mybaitslog#9]
JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@148c9267] will not be managed by Spring
==>  Preparing: select * from selected_data_item where deleted=0 and template_code=? order by sort asc
==> Parameters: 01(String)

插件输出
select
    * 
from
    selected_data_item 
where
    deleted=0 
    and template_code=01 
order by
    sort asc

**Comment by Link-Kou** [comment]
@oday-xiexin  收到，过段时间发布

**Comment by yizhanghong** [comment]
我也测到这个问题了，作者辛苦
