### ISSUE TITLE
抓到了sql,但是没抓到参数

### ISSUE THREAD

**Issue by meiMingle** [Link-Kou/intellij-mybaitslog#91]
如图，抓到的参数是空的。项目地址https://github.com/meiMingle/mpdemo ，测试接口
```http
POST http://localhost:8080/employees/selectByXml
Content-Type: application/x-www-form-urlencoded

param=To
```
![image](https://user-images.githubusercontent.com/39942874/230766866-1af642f8-6d20-4135-baaa-93d6e7e53cb4.png)

**Comment by Link-Kou** [comment]
@meiMingle  我调试一下

**Comment by Link-Kou** [comment]
@FanClys @meiMingle 
手动下载 5.0.7 ，问题已经修复。

**Comment by meiMingle** [comment]
@Link-Kou 5.0.7.1 啥都抓不到了

**Comment by meiMingle** [comment]
控制台命令里面没有那个agent了
![image](https://user-images.githubusercontent.com/39942874/231358020-50a6ec31-5188-4f3f-97a3-34df3f0b4441.png)

**Comment by FanClys** [comment]
![image](https://user-images.githubusercontent.com/47911195/231360580-a06fbb5f-c358-49e0-a274-79016712672c.png)
我能哦
