### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by hetintin** [Link-Kou/intellij-mybaitslog#92]
更新到最新版的插件后，折叠代码的功能很赞。但是，有以下两个遗憾：
1、展开后的格式没有像以前一样格式化，不太方便查看sql
2、使用“Solarized Themes”主题时，部分文字颜色不便于查看
![image](https://user-images.githubusercontent.com/61347434/230856723-bce3c447-8488-4e56-9158-0829f2070800.png)

**Comment by Link-Kou** [comment]
@hetintin 
 颜色可以通过 点击 过滤 图标的按钮进行更换 就在输出控制台左侧
至于 格式化功能，插件里面带了。我没有给开放出来。
后面再给优化一下。
