### ISSUE TITLE
时间转换不正确，如图

### ISSUE THREAD

**Issue by cheakin** [Link-Kou/intellij-mybaitslog#93]
这是我传入的参数：
![image](https://user-images.githubusercontent.com/29295460/231067761-c9821590-378d-46f8-9db8-ec51736b05ff.png)

这是打印出来的SQL（格式化后）：
![image](https://user-images.githubusercontent.com/29295460/231067733-2f111ce9-2858-4eee-9310-3c1996674aaa.png)

**Comment by Link-Kou** [comment]
@cheakin 新版本在时间已经调整为自动
