### ISSUE TITLE
参数指定了jdbcType时无法输出

### ISSUE THREAD

**Issue by mugick** [Link-Kou/intellij-mybaitslog#94]
<img width="434" alt="image" src="https://user-images.githubusercontent.com/45728183/231319759-5f3272b8-09e0-462a-93b8-8858ab33940d.png">
<img width="428" alt="image" src="https://user-images.githubusercontent.com/45728183/231319783-f6452eb2-a7e0-4bf7-8652-3a8ddcc78daf.png">

**Comment by Link-Kou** [comment]
@mugick 你用的插件版本是多少。Mybatis版本是多少。我这里测试没有此问题

**Comment by mugick** [comment]
插件版本5.0.6  mybatis 3.5.7

**Comment by Link-Kou** [comment]
@mugick 感谢，问题的已经定位到，今天修复发布。

**Comment by Link-Kou** [comment]
@mugick 已经发布修复的 5.0.7.1，下载更新即可

**Comment by mugick** [comment]
<img width="518" alt="image" src="https://user-images.githubusercontent.com/45728183/231356511-3dd9e4e3-2bea-40ca-96bb-6401bc794b63.png">
更新版本之后完全不输出了
