### ISSUE TITLE
idea 2023.1

### ISSUE THREAD

**Issue by immortal-oracle** [Link-Kou/intellij-mybaitslog#95]
控制台输出了日志，但是Mybatis log 不输出SQL语句

**Comment by Link-Kou** [comment]
@Xia0HHH 你看一下，控制台的 过滤器 的图标，看看是不是没有勾选boot。
![image](https://user-images.githubusercontent.com/22113151/231337356-d6d9b563-c6e9-4f5d-9d55-92cc22cc70eb.png)

**Comment by Link-Kou** [comment]
@Xia0HHH  看一下 。控制台  是否有输出子关键字
![image](https://user-images.githubusercontent.com/22113151/231349953-1851cbbe-a7a6-4cc2-9993-22ac9f3d0872.png)

**Comment by Link-Kou** [comment]
@Xia0HHH 现在最新的5.0.7.1 试试看

**Comment by Link-Kou** [comment]
@Xia0HHH 你运行一下项目后，按照如图点击打开界面给我截图看看。麻烦了。
![image](https://user-images.githubusercontent.com/22113151/231372966-316eea20-68fb-450f-a050-582ebb9f3a64.png)

**Comment by Link-Kou** [comment]
@Xia0HHH 感谢，我在调测一下，应该是agent没有注入成功。

**Comment by dyl-guang** [comment]
也遇到了同样的问题，Idea 2020.1 版本的，升级了最新的 5.0.7.1，控制台输出了日志，但是Mybatis log 不输出SQL语句

**Comment by Link-Kou** [comment]
@dyl-guang 
现在可以下载最新的5.0.7.2
[MybatisLog-5.0.7.2.zip](https://github.com/Link-Kou/intellij-mybaitslog/files/11220762/MybatisLog-5.0.7.2.zip)

**Comment by Link-Kou** [comment]
@dyl-guang @Xia0HHH  有试试过了吗？现在可以正常打印吗？

**Comment by Link-Kou** [comment]
有弹出提示错误提示之类的。

**Comment by Link-Kou** [comment]
@Xia0HHH 可以给个demo吗，我调试一下。

**Comment by kylin-kai** [comment]
我也是同样情况，回到2.6版本正常

**Comment by Link-Kou** [comment]
@kylin-kai 有什么错误提示吗？

**Comment by WenchaoLau** [comment]
同样问题2个项目1个项目可以正常输出，另外一个就不行
区别如下：
正常输出的是一个单独工程使用 mybatis plus
不正常输出的是一个大的老项目有很多模块，数据源配置了多个，有多个sqlsessionfactory
希望对作者有帮助
