### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by meiMingle** [Link-Kou/intellij-mybaitslog#96]
建议把maven { url 'https://maven.aliyun.com/repository/public/' } 去掉，一些包下不下来，阿里maven仓库里没有，比如
` id 'com.github.johnrengelman.shadow' version '8.1.1'`

去掉gradle.properties 里面的下面的配置 ,其他人导入项目的时候idea会无法正常找到jdk
`org.gradle.java.home=/Library/Java/JavaVirtualMachines/jdk1.8.0_271.jdk/Contents/Home`

**Comment by Link-Kou** [comment]
@meiMingle 因为习惯性。

gradle.properties里面的是指定编译器。默认情况下是jdk17的。
