### ISSUE TITLE
也遇到了同样的问题，控制台输出了日志，但是Mybatis log 不输出SQL语句

### ISSUE THREAD

**Issue by dyl-guang** [Link-Kou/intellij-mybaitslog#98]
也遇到了同样的问题，Idea 2020.1 版本的，升级了最新的 5.0.7.1，控制台输出了日志，但是Mybatis log 不输出SQL语句

**Comment by KingsleyYan** [comment]
2023.1升级到5.0.7.1后也不显示

**Comment by Link-Kou** [comment]
@KingsleyYan @dyl-guang 
此问题已经在定位中了。
我在看问题出在哪里。

**Comment by dyl-guang** [comment]
下载最新的，可以了有SQL日志了，感谢

**Comment by SMSshuai** [comment]
5.0.7.1同样的问题，我查去尝试下5.0.7.2版本

**Comment by SMSshuai** [comment]
5.0.7.2更新后sql正常输出有点问题，不清楚是不是这个插件引起的，无法上传截图，大概描述下就是，mybatis log的控制台输出的sql语句默认被折叠起来了,之前的版本是默认展开的

**Comment by Link-Kou** [comment]
@hetintin  展开合并这个控制我后面看一下如何实现。
还有就是 SQLStructure 本来我是不打印的，奈何还没有找到 一种和与插件通讯的机制。就只好掩耳盗铃
后续版本中我在找寻一种办法处理。
