### ISSUE TITLE
最新版的有个小建议

### ISSUE THREAD

**Issue by SMSshuai** [Link-Kou/intellij-mybaitslog#99]
![image](https://user-images.githubusercontent.com/66891829/232360316-cf4502ab-1ab1-4740-bc7e-35932a5f8680.png)
这个弹出框每次重启项目都要弹出一次，强迫症很难受，都要被迫关闭弹窗，能不能只在编辑器启动的时候弹出一次，或者标记为不再提示，没必要再重启项目的时候一直弹

**Comment by Link-Kou** [comment]
@SMSshuai  你点击一下过滤图标，里面有
![image](https://user-images.githubusercontent.com/22113151/232391399-f9d6a0dc-3686-41c4-8ce9-ca753528846a.png)
去掉就可以了
